### PR TITLE
Adding firebase service to donejs deploy

### PR DESCRIPTION
**Pull request by mjstahl**
Remove divshot packages

Update readme

Fixed some errors where the configuration was not available in package.json

Authentication for firebase

Remove test config from package.json

Finished deployment from package.json

Reading config from firebase.json

### CODE REVIEW

**Comment by mjstahl** [comment]
I still need to add tests.

**Comment by matthewp** [comment]
We don't actually want to remove Divshot yet, it's still working and depend on it for DoneJS chat and place-my-order (for now).  Others might be using it as well so I think we should leave it in until it shuts down.  However if you want to put a warning on the cli or something that would be ok.

**Comment by daffl** [comment]
We also might want to refactor this to work like `donejs add cordova` (e.g. `donejs add deploy firebase`). I don't think it would be too difficult but remove the hard dependency on DoneJS deploy.

**Comment by matthewp** [comment]
@daffl great idea, i've opened a new issue for that https://github.com/donejs/deploy/issues/38 and will do that next.  I'm going to finish the test for this one first.

**Pull request merged**
