### PR TITLE
Fixes #31. Renamed binary to deploy, updated package.json

### LINKED ISSUE #31: Binary should be renamed to deploy
Since the DoneJS CLI now looks for all binaries it looks nicer to be able to type `donejs deploy` instead of `donejs donejs-deploy`.

### PR DESCRIPTION
**Pull request by mjstahl**

### CODE REVIEW

**Comment by matthewp** [comment]
Can you rebase this?

I'm pretty sure this doesn't matter @daffl .  I've been using `donejs deploy` and it works.

**Comment by matthewp** [comment]
Once this is merged I'll release a `0.2.0`

**Comment by mjstahl** [comment]
@matthewp Rebased.

**Comment by matthewp** [comment]
I'll look into the tests.

**Pull request merged**
